### ISSUE TITLE
Issues inspecting the custom resource

### ISSUE THREAD

**Issue by kalise** [cloud-ark/kubeplus#101] opened 2018-10-30 14:59 UTC
Hello, here some issues inspecting the custom resources:

```
$ kubectl get --raw "/apis/kubeplus.cloudark.io/v1/explain?kind=Postgres"
Error from server (NotFound): the server could not find the requested resource
$ kubectl get --raw "/apis/kubeplus.cloudark.io/v1/"
Error from server (NotFound): the server could not find the requested resource
$ kubectl get --raw "/apis/kubeplus.cloudark.io"
{"kind":"APIGroup","apiVersion":"v1","name":"kubeplus.cloudark.io","versions":[{"groupVersion":"kubeplus.cloudark.io/v1","version":"v1"}],"preferredVersion":{"groupVersion":"kubeplus.cloudark.io/v1","version":"v1"}}
```

**Comment by devdattakulkarni** [comment] 2018-10-30 15:13
I changed the api endpoint from kubediscovery to kubeplus. So the kube-discovery-apiserver image needs to be pulled again, if it is present on Minikube.

If you are trying on the previous version of Minikube, I would suggest deleting minikube and trying again as the rc file defines the Image pull as: IfNotPresent. 

Let me know how it goes.

Let me also check on a fresh install of Minikube. Will drop a note here.

**Comment by devdattakulkarni** [comment] 2018-10-30 15:42
Looks like docker hub is having some problems atm. I am getting 403 (forbidden) and 503 (service unavailable) when trying to pull/push any images. Once docker hub is back will update here with my results. Stay tuned.

**Comment by devdattakulkarni** [comment] 2018-11-15 18:07
@kalise I have made several updates recently. I have also added more examples. Can you pull the latest code and try one of the examples? Let me know if anything in the README or example steps is not clear or is incorrect.

**Comment by devdattakulkarni** [comment] 2019-02-10 18:13
@danielpygo: Can you verify if this is still an issue.

**Comment by danielpygo** [comment] 2019-02-11 15:18
Ok, here is my output
```

546 09:15:03 dan@Daniels-MacBook-Pro   (git: master) ~/Desktop/goworkspace/src/github.com/danielpygo/kubeplus/examples/postgres
$ kubectl get pods
NAME                                            READY     STATUS    RESTARTS   AGE
kubeplus-ht8kb                                  4/4       Running   0          2m
postgres-operator-deployment-7649cbf58b-56w6s   1/1       Running   0          52s

547 09:15:17 dan@Daniels-MacBook-Pro   (git: master) ~/Desktop/goworkspace/src/github.com/danielpygo/kubeplus/examples/postgres
$ kubectl get --raw "/apis/kubeplus.cloudark.io/v1/explain?kind=Postgres" | python -m json.tool
{
    "description": "Postgres is a specification for a Postgres resource",
    "properties": {
        "apiVersion": {
            "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
            "type": "string"
        },
        "kind": {
            "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
            "type": "string"
        },
        "spec": {
            "$ref": "#/definitions/typedir.PostgresSpec"
        },
        "status": {
            "$ref": "#/definitions/typedir.PostgresStatus"
        }
    },
    "required": [
        "spec",
        "status"
    ]
}

548 09:15:32 dan@Daniels-MacBook-Pro   (git: master) ~/Desktop/goworkspace/src/github.com/danielpygo/kubeplus/examples/postgres
$ kubectl get --raw "/apis/kubeplus.cloudark.io/v1/"
Error from server (NotFound): the server could not find the requested resource

549 09:15:45 dan@Daniels-MacBook-Pro   (git: master) ~/Desktop/goworkspace/src/github.com/danielpygo/kubeplus/examples/postgres
$ kubectl get --raw "/apis/kubeplus.cloudark.io"
{"kind":"APIGroup","apiVersion":"v1","name":"kubeplus.cloudark.io","versions":[{"groupVersion":"kubeplus.cloudark.io/v1","version":"v1"}],"preferredVersion":{"groupVersion":"kubeplus.cloudark.io/v1","version":"v1"},"serverAddressByClientCIDRs":null}

```

**Comment by devdattakulkarni** [comment] 2019-02-12 13:31
@danielpygo Thanks for verifying that the issue is no longer present.

kubectl get --raw "/apis/kubeplus.cloudark.io/v1/" endpoint is not something that we support. But other two we do. Good to know that they are working as expected.

Closing this issue.

**Closed by devdattakulkarni** 2019-02-12 13:31 UTC
Labels: bug
