### ISSUE TITLE
Kubeplus init is failing when webhook-cert-setup call the mutating webhook service

### ISSUE THREAD

**Issue by enyachoke** [cloud-ark/kubeplus#1122] opened 2023-02-25 14:35 UTC
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1908926/221362443-effdb6f5-8e2d-436f-9c32-0a061bbabf21.png">

```
+ set -e
+ [[ 6 -gt 0 ]]
+ case ${1} in
+ service=crd-hook-service
+ shift
+ shift
+ [[ 4 -gt 0 ]]
+ case ${1} in
+ namespace=kubeplus
+ shift
+ shift
+ [[ 2 -gt 0 ]]
+ case ${1} in
+ secret=webhook-tls-certificates
+ shift
+ shift
+ [[ 0 -gt 0 ]]
++ command -v openssl
+ '[' '!' -x /usr/bin/openssl ']'
+ echo kubeplus
+ echo webhook-tls-certificates
+ echo crd-hook-service
+ csrName=crd-hook-service.kubeplus
+ openssl genrsa -out rootCA.key 4096
kubeplus
webhook-tls-certificates
crd-hook-service
Generating RSA private key, 4096 bit long modulus (2 primes)
............................................++++
........................................++++
e is 65537 (0x010001)
+ openssl req -x509 -new -nodes -key rootCA.key -days 35600 -out rootCA.crt -subj /CN=admission_ca
+ cat
+ openssl genrsa -out server.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
........................+++++
....................................................................................................................................................................................................................................+++++
e is 65537 (0x010001)
+ openssl req -new -key server.key -subj /CN=crd-hook-service.kubeplus.svc -out server.csr -config csr.conf
+ openssl x509 -req -in server.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out serverCrt -days 365 -extensions v3_req -extfile csr.conf
Signature ok
subject=CN = crd-hook-service.kubeplus.svc
Getting CA Private Key
+ openssl x509 -noout -text -in ./serverCrt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            38:1b:6f:0e:55:23:f6:f0:3b:9e:28:12:73:07:6a:93:9e:d0:8e:e6
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = admission_ca
        Validity
            Not Before: Feb 24 04:53:56 2023 GMT
            Not After : Feb 24 04:53:56 2024 GMT
        Subject: CN = crd-hook-service.kubeplus.svc
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:c5:85:93:f7:29:71:86:34:47:91:75:ce:7f:8a:
                    f6:fd:80:b6:42:c7:87:60:b3:5a:19:81:b2:05:f0:
                    f4:49:a9:55:3f:85:7f:c6:f0:5d:b1:e2:f5:5e:3a:
                    dd:00:f7:a9:6f:36:da:b3:f5:58:74:81:c8:fd:12:
                    d7:5e:47:f5:f7:a0:27:40:4a:62:a7:38:0a:d1:15:
                    42:35:93:3c:2e:71:ed:de:2c:60:d2:a0:63:fa:1b:
                    34:36:79:46:54:6b:cf:25:49:11:8f:44:7d:0e:22:
                    bc:be:e7:b6:14:a4:53:43:03:05:32:b2:61:ce:60:
                    68:8b:86:6c:b9:05:de:e9:df:68:be:27:9c:77:bf:
                    19:35:e5:23:84:e6:29:97:cd:4d:ba:12:45:6c:ae:
                    aa:8f:48:d6:e7:66:9f:30:22:89:74:c1:2d:6b:91:
                    b7:8d:df:77:8a:5f:df:a5:05:c3:af:22:98:3e:f2:
+ kubectl delete secret webhook-tls-certificates -n kubeplus
                    04:48:e6:5d:c6:f6:67:d2:32:bc:28:e5:8f:52:bb:
                    19:76:17:63:78:11:7d:f5:47:dc:e4:2a:99:12:ef:
                    de:5a:af:e3:e8:99:9f:9c:98:d7:30:a5:5f:1c:ad:
                    23:10:aa:64:2c:5a:64:4c:07:f3:b9:6d:3e:2a:8d:
                    15:73:0b:d0:3b:d2:15:64:99:f7:f5:37:4e:0d:aa:
                    ff:db
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:crd-hook-service, DNS:crd-hook-service.kubeplus, DNS:crd-hook-service.kubeplus.svc
    Signature Algorithm: sha256WithRSAEncryption
         5b:c7:b3:7a:62:e3:03:e5:eb:c3:20:8b:51:eb:eb:b6:25:24:
         61:33:f4:3c:54:06:f0:30:12:31:df:87:23:3e:b0:f1:2e:94:
         6d:f9:b6:72:d0:df:f2:c2:c8:81:16:ab:81:d5:ba:f2:45:90:
         3f:56:b6:4f:38:dd:63:77:90:2a:5f:ea:e9:66:3c:30:9a:43:
         cc:2a:b9:1c:da:52:75:bb:8d:05:c1:da:47:7d:a5:e3:7c:44:
         89:31:d4:33:59:57:82:b8:4e:ef:d1:47:e7:b0:26:56:29:a4:
         ee:ae:6c:e3:c6:7c:c9:03:9b:7b:60:ef:8d:6a:a2:8b:e6:00:
         59:8d:3e:2d:6a:14:d6:3d:8e:2c:4c:35:b8:b0:bb:82:2c:2f:
         68:76:74:ac:f1:f3:4a:12:70:7a:e1:e5:93:e2:4f:63:04:38:
         cf:90:9d:28:60:7a:11:03:ca:27:39:3c:72:19:95:c9:18:4c:
         ce:3a:09:10:ef:dd:44:6e:7b:5b:44:46:fe:82:e3:54:d7:41:
         19:57:5d:f9:1d:67:bb:d4:10:53:6a:66:1e:a6:e5:bd:bb:d8:
         d5:c6:fd:24:b9:2d:bf:19:ea:1e:cc:c8:3f:8e:ce:5c:fe:92:
         62:ef:fa:67:df:7e:8b:87:63:f8:2b:ac:a9:8d:6f:2e:54:9b:
         15:cd:fb:c3:57:bf:18:48:3b:10:c1:20:eb:9b:4d:7b:c6:14:
         31:ba:a8:3c:b7:8d:fe:8f:99:49:55:9b:f4:d9:41:d8:d8:32:
         91:de:01:ae:e0:58:52:ff:79:e4:0f:95:a7:2e:14:ad:ab:66:
         a0:c8:57:58:bb:9b:8b:85:ab:da:11:78:63:a8:1d:e4:5d:af:
         86:18:9e:54:01:5e:ae:69:b8:5d:ef:ba:2d:20:7c:ea:2a:ee:
         6a:fc:bd:86:e5:f7:bd:65:e3:50:c2:d1:3d:69:2a:6f:e8:d8:
         3a:67:e8:cb:c5:21:16:be:c7:54:18:a4:f7:7d:bb:29:68:45:
         e3:af:fd:52:7d:0f:c8:b1:41:d7:44:49:02:e0:f9:79:e1:39:
         73:e5:e2:1f:c8:3d:af:d7:c4:86:11:01:3d:95:35:e9:b4:57:
         7b:09:b0:69:b1:42:81:7b:ef:0c:5c:21:8c:0d:27:c5:25:fb:
         8e:f1:20:5b:5a:e6:20:f3:be:73:7b:d3:e4:0e:27:c5:c9:e2:
         08:5f:8b:ef:1b:e9:56:17:61:aa:a3:03:e5:30:4a:4d:5d:29:
         43:41:48:ad:37:33:4b:e4:cf:25:6e:6e:b1:30:e5:fc:2c:44:
         51:d3:32:80:16:51:89:6d:34:d3:52:d4:8a:cc:a3:e7:06:38:
         da:b1:73:02:b9:2b:cd:d6
+ true
+ kubectl create secret generic webhook-tls-certificates --from-file=key.pem=server.key --from-file=cert.pem=serverCrt --dry-run=client -o yaml
+ kubectl -n kubeplus apply -f -
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "platform-as-code.crd-binding.v1": failed to call webhook: Post "https://crd-hook-service.kubeplus.svc:443/mutate?timeout=30s": no endpoints available for service "crd-hook-service"

```

**Comment by devdattakulkarni** [comment] 2023-02-25 15:14
Ack.

Can you try with previous versions of KubePlus? 

All the prior versions are available: [https://github.com/cloud-ark/operatorcharts](operatocharts)

3.0.14 should be definitely stable.

**Comment by enyachoke** [comment] 2023-02-25 15:50
BTW the initial deployment worked okay this happened when restarting

**Comment by devdattakulkarni** [comment] 2023-02-26 22:30
I tried install/delete of kubeplus chart (3.0.17) several times but did not see this issue. Each time KubePlus Pod came up in RUNNING state. So not sure what is the root cause of the error. Will leave this issue open - if this error shows up again we can investigate it then.

**Comment by devdattakulkarni** [comment] 2023-03-07 11:31
@enyachoke I ran into this error today after restarting minikube. KubePlus was already deployed;

I am looking into it now.

**Comment by enyachoke** [comment] 2023-03-08 04:42
@devdattakulkarni  I now realise my comment here was not very clear 😄 .
> BTW the initial deployment worked okay this happened when restarting
This was indeed happening when the cluster was restarted after a power cut in my home lab.

**Comment by devdattakulkarni** [comment] 2023-03-08 10:43
I have a fix for this issue. I will push out the changes in a bit.

There is still one aspect that needs to be handled though. It is the following - after the restart of KubePlus, or the cluster, KubePlus's internal state is lost. This leads to the situation where KubePlus is not able to create new instances of an existing CRD. Handling new CRDs and their instances is not a problem. That works as expected.

We have an issue open for this: https://github.com/cloud-ark/kubeplus/issues/1075

**Closed** 2023-03-08 12:28 UTC
